---
- name: Lire configuration CSR1000v
  hosts: routeur
  gather_facts: no
  
  tasks:
    - name: Récupérer la configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: config_output
    
    - name: Afficher la configuration
      debug:
        var: config_output.stdout_lines
    
    - name: Sauvegarder dans un fichier
      copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "./config_csr1000v.txt"
